//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.12.21 at 07:15:45 PM EET 
//


package chatschema;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the chatschema package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Chat_QNAME = new QName("", "Chat");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: chatschema
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link ChatType }
     * 
     */
    public ChatType createChatType() {
        return new ChatType();
    }

    /**
     * Create an instance of {@link SenderType }
     * 
     */
    public SenderType createSenderType() {
        return new SenderType();
    }

    /**
     * Create an instance of {@link ReceiverType }
     * 
     */
    public ReceiverType createReceiverType() {
        return new ReceiverType();
    }

    /**
     * Create an instance of {@link MsgType }
     * 
     */
    public MsgType createMsgType() {
        return new MsgType();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ChatType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Chat")
    public JAXBElement<ChatType> createChat(ChatType value) {
        return new JAXBElement<ChatType>(_Chat_QNAME, ChatType.class, null, value);
    }

}
